### ISSUE TITLE
Possibility to hide the Structure Name "PvName" with IotMqttPublish in the broker

### ISSUE THREAD

**Issue by Sadek-SS** [br-automation-com/paho.mqtt.c-ar#12]
Hi everyone, 
i was wondering if it's Possible to get rid of the Structure Name when i send the Data from my B&R Studio to the MQTT broker.
as you see in the third Photo i always get Exactly the same name as the PvName "MQTT:DriveData": that i defined in my B&R program. but i want to process only the Variables in the Stucture it self only
![Screenshot (33)](https://user-images.githubusercontent.com/85502541/121034843-a36c8580-c7ad-11eb-961f-e86690dd791a.png)
![Screenshot (31)](https://user-images.githubusercontent.com/85502541/121034848-a4051c00-c7ad-11eb-8cde-72f12d4d26f4.png)
![Screenshot (6)](https://user-images.githubusercontent.com/85502541/121035100-d878d800-c7ad-11eb-884f-dce93d87a26d.png)

i would be thankful if i get an answer 

Sadek

**Comment by patricthysell** [comment]
Hi, we had this discussion internally, and for different reasons, we decided not pursue changing the JSON format for the moment, basically I can see the possibility to add that to the PvJson library which is used internally, but it leaves several other configuration possibilities open (that were also requested) -  and the conclusion was, that for the MOMENT - if a specific JSON format is needed, its simpler to use the standard Publish function block and generate the JSON payload from the application.

**Comment by patricthysell** [comment]
@Sadek-SS : I checked some of the other comments, and it seems that this feature is in fact implemented. 
_Regarding RegParSubscribe, it seems to me from what you describe that is working fine. PvName is only used if you choose IOTMQTT_VAR_BINARY. If you set IOTMQTT_VAR_JSON in "DataFormat" parameter, then it's not needed (as the varName is part of the mqtt message)_

This is for sure something to try out
