### ISSUE TITLE
GoogleIOT bring PLC into Service Mode after running Sample Step

### ISSUE THREAD

**Issue by oiyioiyio** [br-automation-com/paho.mqtt.c-ar#18]
Dear Sir,

Follow to your example of GoogleIOT, I try to run at the first step to execute the GoogleIOTCredentials. It is fine but after the task going to step 2, then the PLC go to service mode due to the pointer address problem. Follow to this problem, I need your suggestion to continue diagnostic in my project where I configure wrong. (Test On ARsim)

[IotMqttLog.txt](https://github.com/br-automation-com/paho.mqtt.c-ar/files/8306175/IotMqttLog.txt)

Moreover, I would like to ask to ensure about the certificate and key which are used in the function block. Follow to google instruction link: https://cloud.google.com/iot/docs/how-tos/mqtt-bridge#downloading_mqtt_server_certificates << This give the the roots.pem certificate so I'm I correct that I put to the certificate file address to the function like this?
IotMqttParameters.TLS.CA	:= ADR('//CS:EXT/roots.pem');

I'm confused that in the sample you also provide GoogleIOT.pem so which one should be used in this case?

Lastly, in case of IotMqttParameters.TLS.PrivateKey >> My colleague give me the rsa_private.pem file, is it the correct format for using with this parameter?

P.S. Thank you very much for your effort for this Library.

Best Regards
Teerawat Korkiatthaweechai

**Comment by JobFranken** [comment]
Hello,

For the service mode: Could you please provide a logbook.  A pointer error could come from multiple sources and the logbook provides the feedback where the issue happens. ( In some cases a real target gives a better backtrace location ) 

The 'GoogleIOT.pem' is the root certificate from googles https://pki.goog/roots.pem . So that seems correct
The private key should be generated according to the https://cloud.google.com/iot/docs/concepts/device-security

**Comment by oiyioiyio** [comment]
Dear JobFranken,

Thank you very much for your reply. Follow to your request I face with new problem. Which type of private key needed for GoogleCredential Function Block? I use normal RSA256 without sign private key it seems the JWT output is wrong format.

Moreover, when I put private key to "OwnCerificates/PrivateKeys" it causes the error to the function block, but if I put private key to "ThirdPartyCertificates/SoftwareCertificates" the function block working OK but the output for JWT is not in the correct format and sometime there is no JWT generated from the function block.

![image](https://user-images.githubusercontent.com/78810310/159403995-d0fcbf2e-8135-4aae-b2dd-f9c8a7da33e7.png)

https://user-images.githubusercontent.com/78810310/159404745-2b6fc9f5-fdb9-4722-8720-f4cd62614e88.MP4

I have attached the logger to trace for the previous problem.

[Error.zip](https://github.com/br-automation-com/paho.mqtt.c-ar/files/8321017/Error.zip)

https://user-images.githubusercontent.com/78810310/159406580-193f8803-f7e0-4513-88e4-5ac20d879acc.mp4


Best Regards
Teerawat Korkiatthaweechai

**Comment by JobFranken** [comment]
Issue is reproduced: 
JWT function block generates a password size >250 . This is now temporary fixed for the user by building a test version with a password length of 2500.
