### ISSUE TITLE
Binary file not found

### ISSUE THREAD

**Issue by Th0masis** [br-automation-com/paho.mqtt.c-ar#2]
Hello.
I wanted to test compatibilitz with old Paho library, but i have problem with build. Loger says the binary file of library PahoMQTT could not be found. 
I set in build options right folder and enable declaration of local and global variables.

Do you have any tips what i am missing?
![image](https://user-images.githubusercontent.com/19535887/96414238-232cec00-11ed-11eb-88d3-6fa012004dac.png)

**Comment by alex-gimenez** [comment]
Hello Th0masis,
In the Readme you will find all the required steps to make it work.
All the "undefined reference" errors are due to the missing linker configuration. The warning you're pointing can be solved by removing the library object from the software configuration.
This part of the readme shows how to set it up:
![image](https://user-images.githubusercontent.com/35727022/96510837-6f644480-125e-11eb-8ce0-fe1aa07d539d.png)

**Comment by Th0masis** [comment]
Yeah, i read it. Paho isn't asaifnt to cpu. Build options is set, linker in SampleProgram as well. 

![image](https://user-images.githubusercontent.com/19535887/96549051-3902e580-12af-11eb-92d3-a5859bbc5ecf.png)
![image](https://user-images.githubusercontent.com/19535887/96549062-3ef8c680-12af-11eb-9b97-cf46c9cc14a5.png)
![image](https://user-images.githubusercontent.com/19535887/96549075-44561100-12af-11eb-9c22-6859de133ac6.png)

I dont get ,whats the meaning with Library archives files. Library version/ commpiller - files? (do i need to link them individualy?)

**Comment by alex-gimenez** [comment]
Everything looks fine except the linker configuration. You set up correctly the path but are missing to link the files.
Following image shows how to do it:
![image](https://user-images.githubusercontent.com/35727022/96552601-41115400-12b4-11eb-894d-33dc14e7628b.png)

Please write back with the result

**Comment by alex-gimenez** [comment]
Also, I see you are using a X20CP3586 CPU, then you should use a library version ending with 0. Now you are using one ending with 9, which is meant for industrial PCs. It should compile, however, but it won't connect.
So please, replace the library with 4.73.0 :)

**Comment by Th0masis** [comment]
Yes, its look it help. I still have warning, but build is complete (without errors) :) 
I thought it should be it, bit didint know how to add file, into linker. 

So .0 is for PLC, .1 is ArSim and .9 is for Industrial PC? 

Thank you verry much for fast help 👍

**Comment by alex-gimenez** [comment]
That's it! For future revisions we will use only one library version for every target, (no more .0 .1 or .9), but for rev01 that's how it is.
