### ISSUE TITLE
.a file in wrong format for ARM controller

### ISSUE THREAD

**Issue by bikeortrike** [br-automation-com/paho.mqtt.c-ar#3]
Having an issue when compiling for an X90CP174 controller with ARM processor. The compiler is having an issue with the .a files in the ARM folder of the library:
![image](https://user-images.githubusercontent.com/63927462/97481461-794f0d00-191a-11eb-83b2-35170abe202c.png)

I have successfully compiled and ran using a PC and successfully compiled for an X20CP1584 (Atom processor).

Thanks

**Comment by alex-gimenez** [comment]
Hi, please tell us which library version are you using?
Please bear in mind that for PLCs (Intel or ARM) a library version ending with .0 must be used.
I suspect you could be using one ending with .9, which is used with industrial PCs (and aren't prepared for ARM targets).

**Comment by bikeortrike** [comment]
Hello Alex,
Thanks for the reply. I'm using V4.73.0. I initially used the existing library that was in the sample provided (V4.73.9) but received errors (I believe they were Function not declared errors) during compile. I replaced it with V4.73.0 and now receive the errors noted. As mentioned, I successfully compiled when using an X20CP1584 controller (Atom Processor) using the same V4.73.0 library.
Thanks for the help.

**Comment by alex-gimenez** [comment]
You need to set compiler version to 6.3.0 for it to work. You can do it in Project -> Change Runtime version
![image](https://user-images.githubusercontent.com/35727022/97892092-de966a00-1d2f-11eb-8b45-60938aee250f.png)

Please tell me if this solves the issue, it did in my case :)

**Comment by bikeortrike** [comment]
Thanks for the continued support.

Unfortunately I still get an error. It is slightly different:
![image](https://user-images.githubusercontent.com/63927462/97894657-fea63900-1cef-11eb-9238-859c05a00b2e.png)

""adding symbols" instead of "could not read symbols"...

I cleaned and rebuilt but same errors...

**Comment by bikeortrike** [comment]
Correction, I recopied the library files and tried again. This time, success!

Thanks for the support.
